### ISSUE TITLE
Make cross refs (links) distinguishable from normal code snippets (no links).

### ISSUE THREAD

**Issue by sscherfke** [rtfd/sphinx_rtd_theme#153]
Currently, normal code snippets (e.g., `''asdf''`) are render the same way like cross ref links (e.g., `:class:'spam.Spam'`). This makes it hard for users to identify that these are links and that they can click on them to get more information.

Maybe it would be enough to make the border the same color as normal links.

**Comment by patricksnape** [comment]
Bumping this. Under the following set up:

Sphinx==1.3b2
sphinx-rtd-theme==0.1.6
Pygments==2.0.2
using the Napolean extension

on Ubuntu 14.04 x64.

It makes the documentation nearly unreadable because it is impossible to distinguish between cross-references and code. Also, I am not very fond of the red colouring for inline code as I think it makes it less readable.

**Comment by jessetan** [comment]
Does not look like a problem anymore:
![current behavior](https://user-images.githubusercontent.com/3284111/34160417-249eba96-e4cd-11e7-8435-8e26f71c0111.png)
Closing this issue, please reopen if this resurfaces.
