### ISSUE TITLE
Extending footer

### ISSUE THREAD

**Issue by martini5468** [rtfd/sphinx_rtd_theme#395]
I am using rtd theme in a local Sphinx deployment. I would like to extend the footer to show a git commit hash similar to <https://readthedocs.org/>. I can see in `footer.html` there are a few template tags like `build_url`, `build_id`, `commit`. I think `commit` should do the trick however I am not sure how to assign a value for `commit` and have it display. Where can I find some more information how to do that?

**Comment by TomRichter** [comment]
These variables can be populated in `conf.py` via the `html_context` dict.

`footer.html` tries to display ONLY ONE of the following version lines, in order:
 * A link to the relevant build server build, if `build_id` AND `build_url` are set.
 * A commit hash, if `commit` is set.
 * A datetime stamp, if `last_updated` is set.  But see [html_last_updated_fmt](http://www.sphinx-doc.org/en/stable/config.html#confval-html_last_updated_fmt) instead of setting `last_updated` manually.

For example, let's include the latest commit hash in the footer when Travis CI crunches the docs.  Many build servers set environment variables with each build's information, so we just need to [find the right one](https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables) and use [`os.getenv()`](https://docs.python.org/2/library/os.html#os.getenv) to pull it into `conf.py` at build time:

```python
import os

html_context = {
    # Need to trim the commit hash to normal size since TRAVIS_COMMIT contains the full
    # length hash, which is really long!
    
    # Default value is empty string, which won't trigger the commit footer if TRAVIS_COMMIT
    # isn't set and won't explode on slice like None would.
    'commit': os.getenv('TRAVIS_COMMIT', '')[:7],
}
```

Even if your "local deployment" doesn't include a build server setting environment variables, there are [other options](https://stackoverflow.com/q/14989858) for getting the commit hash itself.

**Comment by martini5468** [comment]
Thanks @TomRichter your explanation was very clear. I was able to populate the hash in `conf.py` by using the `GIT_COMMIT` env variable provided by the git module in Jenkins.

**Comment by 1138-4EB** [comment]
I'd like to reproduce this, but getting a probably different commit hash for each file: the one corresponding to the last time the file was modified; instead of using the same hash for all the pages. Is this supported through either `conf.py` or modifying the template?
