### ISSUE TITLE
Content Security Policy support

### ISSUE THREAD

**Issue by rudolphfroger** [rtfd/sphinx_rtd_theme#414]
It would be good to allow users of this theme to implement a Content Security Policy which disallows inline javascript, since that should prevent injected javascript from being executed. Removing inline CSS styles would also be nice. I've searched through the repository of sphinx_rtd_theme and I think the number of inline scripts and styles is already low so my first guess is that this change shouldn't be too much work.

I can help you with testing the changes against a Content Security Policy.

Also see https://github.com/rtfd/readthedocs.org/issues/2793

**Comment by Blendify** [comment]
As stated in #500 I would want to see sphinx adopt this first so we can just inherit the HTML code.
So this is not a bug for us but for sphinx.

**Comment by remyabel** [comment]
The fix has now been merged in Sphinx: https://github.com/sphinx-doc/sphinx/issues/3620

**Comment by Blendify** [comment]
Ok, once #545 is merged we can also adopt this.

**Comment by davidfischer** [comment]
I'm a big fan of [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) but I do want to just note some challenges and design decisions that will need to be addressed in order to fully adopt CSP.

To give just a little background, CSP basically lets a server set an HTTP header (or less commonly it can be specified by `<meta>`) dictate where scripts and CSS can be loaded.  This is typically used to completely disable inline CSS/JS or to ensure that CSS/JS files are only loaded from the same origin or a whitelisted set of origins. One note is that this can mean that external JS files cannot set inline styles as well. The big advantage of CSP is it makes exploiting a XSS vulnerability much harder.

* The first and most clear step is to make sure we have no inline CSS and JS. This is essentially all Sphinx did. We have relatively few inline CSS/JS so this shouldn't be too hard.
* Should the theme add the `<meta>` tag? I'm -1 on this as we do have users who inline JS/CSS. Should it be an option? I'm less opposed to that.
* Should readthedocs.io send the CSP header? I'm -1 on that too. If we just turned that on, a lot of things would probably break like past documentation and existing inlines people have.

**Comment by remyabel** [comment]
@davidfischer I agree with your concerns. A global policy would be bad because no one policy will work for all users. It would have to be custom for each page. You can adopt the Github Pages approach and use a conservative CSP served via header and more tech-savvy users can use a `<meta>` tag. For unprotected pages, not much can be done about that. For example, tumblr has the ability to enable HTTPS, but not by default because users that post `http` links will complain that things are broken.

**Comment by rudolphfroger** [comment]
I agree with @davidfischer. The goal should to remove all inline CSS and JS and making sure no "eval" is used in Javascript. This enables people to enforce a strict CSP.

**Comment by remyabel** [comment]
The only other part of the RTD theme AFAIK that violates CSP is Modernizr because it injects inline styles. Also see https://github.com/rtfd/sphinx_rtd_theme/issues/525. Once the patch is merged and Modernizr is removed, we should be good to go.
