### ISSUE TITLE
Edititing CSS file

### ISSUE THREAD

**Issue by nluetzge** [rtfd/sphinx_rtd_theme#483]
Hi!

Love the theme but would like to  make some small edits to customize it (change colors and add logos and things like that) I made a local copy of the theme and started editing and I usually don't have a problem editing css files with a text editor but this one is different from the ones I know. There seems to be no formatting and everything is in a very long line which  makes it hard to edit. Am I missing something? What do you use to edit the css file sheet?

Thanks alot!
Cheers, 
Nora

**Comment by Blendify** [comment]
The easiest way to do this is to override the theme css. To do this create a new css file and tell sphinx about it with http://www.sphinx-doc.org/en/stable/extdev/appapi.html#sphinx.application.Sphinx.add_stylesheet

**Comment by nluetzge** [comment]
Hm but wouldn't that still mean that I have to copy the CSS from you and edit it? Also, I have tried this with a different theme before and it didn't really work. It took the new CSS but it also took the old CSS and I was not really sure how to change things like that.

**Comment by Blendify** [comment]
Ok, if that is not what you want you can add this project as a [Git Submodule](https://git-scm.com/docs/git-submodule) then use `html_themepath` to point to the `sphinx_rtd_theme` subfolder of this project. You can then make a branch for the theme and make your edits. The thing is that we do not use CSS directly but we use [SASS](http://sass-lang.com/). This means that you will have to compile the modified sass-files to css-files. See the readme of this project for more information on how to do this.

Because this is more complicated I just gave you the easy answer which still can be done by the way.

> It took the new CSS but it also took the old CSS and I was not really sure how to change things like that.

You would have to see what CSS properties are defined for a specific element and replace it with something else. For example, to change the color of the blue region with the search bar to green create a css file with:

```
.wy-side-nav-search {
    background-color: green;
}
```

Here is a longer example of a project I contribute to: https://developer.blender.org/diffusion/BM/browse/trunk/blender_docs/resources/theme/css/theme_overrides.css
