### ISSUE TITLE
How to justify the text alignment?

### ISSUE THREAD

**Issue by tonyriverms** [rtfd/sphinx_rtd_theme#646]
It looks the theme left-aligns the text. Is it possible that the text can be "justified" like in various Word processors at this moment, through css configuration or else?

I see here https://github.com/rtfd/sphinx_rtd_theme/labels/PR%3A%20work%20in%20progress there is in-progress work to make the text right-to-left aligned.

**Comment by jessetan** [comment]
> t looks the theme left-aligns the text. Is it possible that the text can be "justified" like in various Word processors at this moment, through css configuration or else?

There is no theme option to change text alignment, but you can influence it if you supply a custom CSS file that sets `text-align: justify` for the elements you wish to have changed. Note that justified text on the web is generally discouraged because browsers do not produce very readable results.

> I see here https://github.com/rtfd/sphinx_rtd_theme/labels/PR%3A%20work%20in%20progress there is in-progress work to make the text right-to-left aligned.

If you are referring to #498, that issue is about support for languages that are written right-to-left, not right alignment of left-to-right text. Text will be right aligned in that case, but does not support either justified or left aligned text.
